/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.101.1
  Forc version: 0.68.1
  Fuel-Core version: 0.43.1
*/

import { Contract as __Contract, Interface } from "fuels";
import type {
  Provider,
  Account,
  StorageSlot,
  Address,
  BigNumberish,
  BN,
  Bytes,
  FunctionFragment,
  InvokeFunction,
} from 'fuels';

import type { Enum, Vec } from "./common";

export enum ErrorInput { OrderNotDefined = 'OrderNotDefined', OrderReenter = 'OrderReenter', TryToFillMoreThanRequired = 'TryToFillMoreThanRequired', SentAssetIdDoesNotMatchMakerToken = 'SentAssetIdDoesNotMatchMakerToken', SentAssetAmountDoesNotMatchFillAmount = 'SentAssetAmountDoesNotMatchFillAmount', InsufficientTakerTokensReceivedFromCallback = 'InsufficientTakerTokensReceivedFromCallback', OnlySettlementCanInteract = 'OnlySettlementCanInteract', AlreadyIntitialized = 'AlreadyIntitialized', MakerHasNotEnoughFunds = 'MakerHasNotEnoughFunds' };
export enum ErrorOutput { OrderNotDefined = 'OrderNotDefined', OrderReenter = 'OrderReenter', TryToFillMoreThanRequired = 'TryToFillMoreThanRequired', SentAssetIdDoesNotMatchMakerToken = 'SentAssetIdDoesNotMatchMakerToken', SentAssetAmountDoesNotMatchFillAmount = 'SentAssetAmountDoesNotMatchFillAmount', InsufficientTakerTokensReceivedFromCallback = 'InsufficientTakerTokensReceivedFromCallback', OnlySettlementCanInteract = 'OnlySettlementCanInteract', AlreadyIntitialized = 'AlreadyIntitialized', MakerHasNotEnoughFunds = 'MakerHasNotEnoughFunds' };

export type AddressInput = { bits: string };
export type AddressOutput = AddressInput;
export type LimitOrderInput = { maker_token: string, taker_token: string, maker_amount: BigNumberish, taker_amount: BigNumberish, maker: AddressInput, taker: AddressInput, nonce: BigNumberish, expriy: BigNumberish };
export type LimitOrderOutput = { maker_token: string, taker_token: string, maker_amount: BN, taker_amount: BN, maker: AddressOutput, taker: AddressOutput, nonce: BN, expriy: BN };
export type OrderFillReturnInput = { taker_fill_amount: BigNumberish, maker_fill_amount: BigNumberish };
export type OrderFillReturnOutput = { taker_fill_amount: BN, maker_fill_amount: BN };

const abi = {
  "programType": "contract",
  "specVersion": "1",
  "encodingVersion": "1",
  "concreteTypes": [
    {
      "type": "()",
      "concreteTypeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
    },
    {
      "type": "b256",
      "concreteTypeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
    },
    {
      "type": "enum order_utils::structs::Error",
      "concreteTypeId": "d17bf44120afbfa277bb39f5f550f3e6e94f72654087b8846c4169da43e155fe",
      "metadataTypeId": 0
    },
    {
      "type": "struct order_utils::structs::LimitOrder",
      "concreteTypeId": "c354cc22a41e93a53205acdc55aab95d1476275ccaae65bf4c3e1c1b7acc5c69",
      "metadataTypeId": 3
    },
    {
      "type": "struct order_utils::structs::OrderFillReturn",
      "concreteTypeId": "10633495056fa383212cf2f1f0adc29621b9fb4daf2f01665012d78e7d1f369c",
      "metadataTypeId": 4
    },
    {
      "type": "struct std::address::Address",
      "concreteTypeId": "f597b637c3b0f588fb8d7086c6f4735caa3122b85f0423b82e489f9bb58e2308",
      "metadataTypeId": 5
    },
    {
      "type": "struct std::bytes::Bytes",
      "concreteTypeId": "cdd87b7d12fe505416570c294c884bca819364863efe3bf539245fa18515fbbb",
      "metadataTypeId": 6
    },
    {
      "type": "struct std::vec::Vec<b256>",
      "concreteTypeId": "32559685d0c9845f059bf9d472a0a38cf77d36c23dfcffe5489e86a65cdd9198",
      "metadataTypeId": 9,
      "typeArguments": [
        "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
      ]
    },
    {
      "type": "struct std::vec::Vec<u64>",
      "concreteTypeId": "d5bfe1d4e1ace20166c9b50cadd47e862020561bde24f5189cfc2723f5ed76f4",
      "metadataTypeId": 9,
      "typeArguments": [
        "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
      ]
    },
    {
      "type": "u64",
      "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
    }
  ],
  "metadataTypes": [
    {
      "type": "enum order_utils::structs::Error",
      "metadataTypeId": 0,
      "components": [
        {
          "name": "OrderNotDefined",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "OrderReenter",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "TryToFillMoreThanRequired",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "SentAssetIdDoesNotMatchMakerToken",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "SentAssetAmountDoesNotMatchFillAmount",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "InsufficientTakerTokensReceivedFromCallback",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "OnlySettlementCanInteract",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "AlreadyIntitialized",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "MakerHasNotEnoughFunds",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        }
      ]
    },
    {
      "type": "generic T",
      "metadataTypeId": 1
    },
    {
      "type": "raw untyped ptr",
      "metadataTypeId": 2
    },
    {
      "type": "struct order_utils::structs::LimitOrder",
      "metadataTypeId": 3,
      "components": [
        {
          "name": "maker_token",
          "typeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        },
        {
          "name": "taker_token",
          "typeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        },
        {
          "name": "maker_amount",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "taker_amount",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "maker",
          "typeId": 5
        },
        {
          "name": "taker",
          "typeId": 5
        },
        {
          "name": "nonce",
          "typeId": 10
        },
        {
          "name": "expriy",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ]
    },
    {
      "type": "struct order_utils::structs::OrderFillReturn",
      "metadataTypeId": 4,
      "components": [
        {
          "name": "taker_fill_amount",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "maker_fill_amount",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ]
    },
    {
      "type": "struct std::address::Address",
      "metadataTypeId": 5,
      "components": [
        {
          "name": "bits",
          "typeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        }
      ]
    },
    {
      "type": "struct std::bytes::Bytes",
      "metadataTypeId": 6,
      "components": [
        {
          "name": "buf",
          "typeId": 7
        },
        {
          "name": "len",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ]
    },
    {
      "type": "struct std::bytes::RawBytes",
      "metadataTypeId": 7,
      "components": [
        {
          "name": "ptr",
          "typeId": 2
        },
        {
          "name": "cap",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ]
    },
    {
      "type": "struct std::vec::RawVec",
      "metadataTypeId": 8,
      "components": [
        {
          "name": "ptr",
          "typeId": 2
        },
        {
          "name": "cap",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ],
      "typeParameters": [
        1
      ]
    },
    {
      "type": "struct std::vec::Vec",
      "metadataTypeId": 9,
      "components": [
        {
          "name": "buf",
          "typeId": 8,
          "typeArguments": [
            {
              "name": "",
              "typeId": 1
            }
          ]
        },
        {
          "name": "len",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ],
      "typeParameters": [
        1
      ]
    },
    {
      "type": "u256",
      "metadataTypeId": 10
    }
  ],
  "functions": [
    {
      "inputs": [
        {
          "name": "order_hash",
          "concreteTypeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        },
        {
          "name": "amount",
          "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "receiver",
          "concreteTypeId": "f597b637c3b0f588fb8d7086c6f4735caa3122b85f0423b82e489f9bb58e2308"
        },
        {
          "name": "callback_data",
          "concreteTypeId": "cdd87b7d12fe505416570c294c884bca819364863efe3bf539245fa18515fbbb"
        }
      ],
      "name": "fill_single",
      "output": "10633495056fa383212cf2f1f0adc29621b9fb4daf2f01665012d78e7d1f369c",
      "attributes": [
        {
          "name": "allow",
          "arguments": [
            "deprecated"
          ]
        },
        {
          "name": "storage",
          "arguments": [
            "write",
            "read"
          ]
        },
        {
          "name": "payable",
          "arguments": []
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "order",
          "concreteTypeId": "c354cc22a41e93a53205acdc55aab95d1476275ccaae65bf4c3e1c1b7acc5c69"
        }
      ],
      "name": "get_order_hash",
      "output": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "registry",
          "concreteTypeId": "f597b637c3b0f588fb8d7086c6f4735caa3122b85f0423b82e489f9bb58e2308"
        }
      ],
      "name": "initialize",
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "order",
          "concreteTypeId": "c354cc22a41e93a53205acdc55aab95d1476275ccaae65bf4c3e1c1b7acc5c69"
        }
      ],
      "name": "pack_order",
      "output": "cdd87b7d12fe505416570c294c884bca819364863efe3bf539245fa18515fbbb",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "order_hashes",
          "concreteTypeId": "32559685d0c9845f059bf9d472a0a38cf77d36c23dfcffe5489e86a65cdd9198"
        },
        {
          "name": "amounts",
          "concreteTypeId": "d5bfe1d4e1ace20166c9b50cadd47e862020561bde24f5189cfc2723f5ed76f4"
        }
      ],
      "name": "register_filling",
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "order_hashes",
          "concreteTypeId": "32559685d0c9845f059bf9d472a0a38cf77d36c23dfcffe5489e86a65cdd9198"
        },
        {
          "name": "amounts",
          "concreteTypeId": "d5bfe1d4e1ace20166c9b50cadd47e862020561bde24f5189cfc2723f5ed76f4"
        }
      ],
      "name": "verify_settlement",
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "write"
          ]
        }
      ]
    }
  ],
  "loggedTypes": [
    {
      "logId": "15094927136620789666",
      "concreteTypeId": "d17bf44120afbfa277bb39f5f550f3e6e94f72654087b8846c4169da43e155fe"
    }
  ],
  "messagesTypes": [],
  "configurables": []
};

const storageSlots: StorageSlot[] = [
  {
    "key": "76b192ef8bf151b53d0d92f994bf2923c7b4f279887cb0a721779effd4624897",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  }
];

export class OrderSettlementInterface extends Interface {
  constructor() {
    super(abi);
  }

  declare functions: {
    fill_single: FunctionFragment;
    get_order_hash: FunctionFragment;
    initialize: FunctionFragment;
    pack_order: FunctionFragment;
    register_filling: FunctionFragment;
    verify_settlement: FunctionFragment;
  };
}

export class OrderSettlement extends __Contract {
  static readonly abi = abi;
  static readonly storageSlots = storageSlots;

  declare interface: OrderSettlementInterface;
  declare functions: {
    fill_single: InvokeFunction<[order_hash: string, amount: BigNumberish, receiver: AddressInput, callback_data: Bytes], OrderFillReturnOutput>;
    get_order_hash: InvokeFunction<[order: LimitOrderInput], string>;
    initialize: InvokeFunction<[registry: AddressInput], void>;
    pack_order: InvokeFunction<[order: LimitOrderInput], Bytes>;
    register_filling: InvokeFunction<[order_hashes: Vec<string>, amounts: Vec<BigNumberish>], void>;
    verify_settlement: InvokeFunction<[order_hashes: Vec<string>, amounts: Vec<BigNumberish>], void>;
  };

  constructor(
    id: string | Address,
    accountOrProvider: Account | Provider,
  ) {
    super(id, abi, accountOrProvider);
  }
}
