/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.101.1
  Forc version: 0.68.1
  Fuel-Core version: 0.43.1
*/

import { Contract as __Contract, Interface } from "fuels";
import type {
  Provider,
  Account,
  StorageSlot,
  Address,
  BigNumberish,
  BN,
  FunctionFragment,
  InvokeFunction,
} from 'fuels';

import type { Enum } from "./common";

export enum ErrorInput { OrderNotDefined = 'OrderNotDefined', OrderReenter = 'OrderReenter', TryToFillMoreThanRequired = 'TryToFillMoreThanRequired', SentAssetIdDoesNotMatchMakerToken = 'SentAssetIdDoesNotMatchMakerToken', SentAssetAmountDoesNotMatchFillAmount = 'SentAssetAmountDoesNotMatchFillAmount', InsufficientTakerTokensReceivedFromCallback = 'InsufficientTakerTokensReceivedFromCallback', OnlySettlementCanInteract = 'OnlySettlementCanInteract', AlreadyIntitialized = 'AlreadyIntitialized', MakerHasNotEnoughFunds = 'MakerHasNotEnoughFunds' };
export enum ErrorOutput { OrderNotDefined = 'OrderNotDefined', OrderReenter = 'OrderReenter', TryToFillMoreThanRequired = 'TryToFillMoreThanRequired', SentAssetIdDoesNotMatchMakerToken = 'SentAssetIdDoesNotMatchMakerToken', SentAssetAmountDoesNotMatchFillAmount = 'SentAssetAmountDoesNotMatchFillAmount', InsufficientTakerTokensReceivedFromCallback = 'InsufficientTakerTokensReceivedFromCallback', OnlySettlementCanInteract = 'OnlySettlementCanInteract', AlreadyIntitialized = 'AlreadyIntitialized', MakerHasNotEnoughFunds = 'MakerHasNotEnoughFunds' };

export type AddressInput = { bits: string };
export type AddressOutput = AddressInput;
export type LimitOrderInput = { maker_token: string, taker_token: string, maker_amount: BigNumberish, taker_amount: BigNumberish, maker: AddressInput, taker: AddressInput, nonce: BigNumberish, expriy: BigNumberish };
export type LimitOrderOutput = { maker_token: string, taker_token: string, maker_amount: BN, taker_amount: BN, maker: AddressOutput, taker: AddressOutput, nonce: BN, expriy: BN };

const abi = {
  "programType": "contract",
  "specVersion": "1",
  "encodingVersion": "1",
  "concreteTypes": [
    {
      "type": "()",
      "concreteTypeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
    },
    {
      "type": "b256",
      "concreteTypeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
    },
    {
      "type": "enum order_utils::structs::Error",
      "concreteTypeId": "d17bf44120afbfa277bb39f5f550f3e6e94f72654087b8846c4169da43e155fe",
      "metadataTypeId": 0
    },
    {
      "type": "struct order_utils::structs::LimitOrder",
      "concreteTypeId": "c354cc22a41e93a53205acdc55aab95d1476275ccaae65bf4c3e1c1b7acc5c69",
      "metadataTypeId": 1
    },
    {
      "type": "struct std::address::Address",
      "concreteTypeId": "f597b637c3b0f588fb8d7086c6f4735caa3122b85f0423b82e489f9bb58e2308",
      "metadataTypeId": 2
    },
    {
      "type": "u64",
      "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
    }
  ],
  "metadataTypes": [
    {
      "type": "enum order_utils::structs::Error",
      "metadataTypeId": 0,
      "components": [
        {
          "name": "OrderNotDefined",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "OrderReenter",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "TryToFillMoreThanRequired",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "SentAssetIdDoesNotMatchMakerToken",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "SentAssetAmountDoesNotMatchFillAmount",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "InsufficientTakerTokensReceivedFromCallback",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "OnlySettlementCanInteract",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "AlreadyIntitialized",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "MakerHasNotEnoughFunds",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        }
      ]
    },
    {
      "type": "struct order_utils::structs::LimitOrder",
      "metadataTypeId": 1,
      "components": [
        {
          "name": "maker_token",
          "typeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        },
        {
          "name": "taker_token",
          "typeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        },
        {
          "name": "maker_amount",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "taker_amount",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "maker",
          "typeId": 2
        },
        {
          "name": "taker",
          "typeId": 2
        },
        {
          "name": "nonce",
          "typeId": 3
        },
        {
          "name": "expriy",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ]
    },
    {
      "type": "struct std::address::Address",
      "metadataTypeId": 2,
      "components": [
        {
          "name": "bits",
          "typeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        }
      ]
    },
    {
      "type": "u256",
      "metadataTypeId": 3
    }
  ],
  "functions": [
    {
      "inputs": [
        {
          "name": "hash",
          "concreteTypeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        }
      ],
      "name": "cancel_order",
      "output": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "write"
          ]
        },
        {
          "name": "payable",
          "arguments": []
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "expriy",
          "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "taker_amount",
          "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "taker_asset",
          "concreteTypeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        },
        {
          "name": "taker",
          "concreteTypeId": "f597b637c3b0f588fb8d7086c6f4735caa3122b85f0423b82e489f9bb58e2308"
        }
      ],
      "name": "create_order",
      "output": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "write"
          ]
        },
        {
          "name": "payable",
          "arguments": []
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "hash",
          "concreteTypeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        }
      ],
      "name": "get_order",
      "output": "c354cc22a41e93a53205acdc55aab95d1476275ccaae65bf4c3e1c1b7acc5c69",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "settlement",
          "concreteTypeId": "f597b637c3b0f588fb8d7086c6f4735caa3122b85f0423b82e489f9bb58e2308"
        }
      ],
      "name": "initialize",
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "maker",
          "concreteTypeId": "f597b637c3b0f588fb8d7086c6f4735caa3122b85f0423b82e489f9bb58e2308"
        },
        {
          "name": "maker_asset",
          "concreteTypeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        },
        {
          "name": "maker_amount",
          "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "receiver",
          "concreteTypeId": "f597b637c3b0f588fb8d7086c6f4735caa3122b85f0423b82e489f9bb58e2308"
        }
      ],
      "name": "pull_maker_funds",
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "write"
          ]
        }
      ]
    }
  ],
  "loggedTypes": [
    {
      "logId": "15094927136620789666",
      "concreteTypeId": "d17bf44120afbfa277bb39f5f550f3e6e94f72654087b8846c4169da43e155fe"
    }
  ],
  "messagesTypes": [],
  "configurables": []
};

const storageSlots: StorageSlot[] = [
  {
    "key": "04457c69a904b2a907aa0a06c823b6a5d0c1549a98865c4517449500eff1c277",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  }
];

export class OrderRegistryInterface extends Interface {
  constructor() {
    super(abi);
  }

  declare functions: {
    cancel_order: FunctionFragment;
    create_order: FunctionFragment;
    get_order: FunctionFragment;
    initialize: FunctionFragment;
    pull_maker_funds: FunctionFragment;
  };
}

export class OrderRegistry extends __Contract {
  static readonly abi = abi;
  static readonly storageSlots = storageSlots;

  declare interface: OrderRegistryInterface;
  declare functions: {
    cancel_order: InvokeFunction<[hash: string], string>;
    create_order: InvokeFunction<[expriy: BigNumberish, taker_amount: BigNumberish, taker_asset: string, taker: AddressInput], string>;
    get_order: InvokeFunction<[hash: string], LimitOrderOutput>;
    initialize: InvokeFunction<[settlement: AddressInput], void>;
    pull_maker_funds: InvokeFunction<[maker: AddressInput, maker_asset: string, maker_amount: BigNumberish, receiver: AddressInput], void>;
  };

  constructor(
    id: string | Address,
    accountOrProvider: Account | Provider,
  ) {
    super(id, abi, accountOrProvider);
  }
}
