packages:
  - 'frontend'
  - 'backend'

overrides:
  'bn.js@5.2.1': 5.2.5
  'fflate@0.8.2': 0.8.3
  'glob@10.4.5': 10.5.0
  'handlebars@4.7.8': 4.7.9
  'ws@8': 8.21.3
  '@walletconnect/utils>query-string': 9.5.1
  'fuels>toml': 4.3.0
  '@metamask/sdk>uuid': 11.1.1
  '@metamask/sdk-communication-layer>uuid': 11.1.1
  '@metamask/utils>uuid': 11.1.1